FROM node:20-alpine AS builder

WORKDIR /usr/src/app-front

COPY ./package.json ./package-lock.json .

RUN npm ci

COPY . .

RUN npm run build



FROM node:20-alpine AS runner

WORKDIR /usr/src/app-front

COPY --from=builder /usr/src/app-front/dist .