version: "3.9"
services:

  database:
    image: "postgres"
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
      - ./backend/test/initSQL.sql:/docker-entrypoint-initdb.d/initSQL.sql
    environment:
      POSTGRES_USER: "student"
      POSTGRES_PASSWORD: "student"

  backend:
    build: "./backend"
    ports:
      - "3000:3000"
    env_file: 
    - "backend/.env"
    depends_on:
      - database

  frontend:
    build: "./frontend"
    env_file: "frontend/.env"
    volumes:
      - frontend_dist:/usr/src/app-front

  nginx:
    image: "nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend_dist:/var/www/frontend

volumes:
  frontend_dist:
  postgres_data: