FROM node:20-alpine AS builder

WORKDIR /usr/src/app-back

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /usr/src/app-back

COPY --from=builder /usr/src/app-back/package*.json ./

RUN npm i --omit=dev

COPY --from=builder /usr/src/app-back/public ./public
COPY --from=builder /usr/src/app-back/dist ./dist

EXPOSE 3000

CMD [ "node", "./dist/src/main.js" ] 