events {
    worker_connections  1024;
}

http {

    include mime.types;

    server {

        listen 80 default_server;
        listen [::]:80;

        server_name osmaxfilm.nomorepartiessbs.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri $uri/;
        }

        location / {
            root /var/www/frontend;
            try_files $uri $uri/ /index.html;
        }

    }

    server {

        listen 80;

        server_name api.localhost;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri $uri/;
        }

        location /afisha/ {

                add_header 'Access-Control-Allow-Origin' "*" always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
		        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;

                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';

                if ($request_method = 'OPTIONS') {
                        return 204;
                }

                proxy_pass http://localhost:3000;
                proxy_set_header Host osmaxfilm.nomorepartiessbs.ru;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /content/afisha/ {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT';

                proxy_pass https://localhost:3000;
                proxy_set_header Host osmaxfilm.nomorepartiessbs.ru;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}
